class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'welcome': 'Welcome to EchoSpeak',
      'welcome_sub':
          'Practice speaking and improve your pronunciation, one sentence at a time.',
      'start_speaking': 'Start Speaking',
      'what_you_can_do': 'What you can do',
      'feature_1': 'Listen to correct pronunciation',
      'feature_2': 'Practice speaking out loud',
      'feature_3': 'Track your attempts',
      'home': 'Home',
      'practice': 'Practice',
      'results': 'Results',
      'settings': 'Settings',
      'listen': 'Listen',
      'speak': 'Speak',
      'stop': 'Stop',
      'recording_saved': 'Recording saved successfully!',
      'try_again': 'Try Again',
      'next_sentence': 'Next Sentence',
      'good_job': 'Good job!',
      'no_result_yet': 'Complete a practice sentence to see your result here.',
      'sound': 'Sound',
      'language': 'Interface Language',
      'choose_language': 'Choose your app language',
      'about': 'About EchoSpeak',
      'about_text':
          'EchoSpeak helps you practice English speaking, one short sentence at a time.',
      'mic_permission_title': 'Microphone permission needed',
      'mic_permission_body':
          'EchoSpeak needs microphone access to record your practice. Please allow it from your device settings.',
      'ok': 'OK',
      'open_settings': 'Open Settings',
    },

    'ar': {
      'welcome': 'مرحبًا بك في EchoSpeak',
      'welcome_sub': 'تدرّب على التحدث وحسّن نطقك، جملةً بعد جملة.',
      'start_speaking': 'ابدأ التدريب',
      'what_you_can_do': 'ماذا تستطيع أن تفعل',
      'feature_1': 'استمع إلى النطق الصحيح',
      'feature_2': 'تدرّب على التحدث بصوت عالٍ',
      'feature_3': 'تابع محاولاتك',
      'home': 'الرئيسية',
      'practice': 'التدريب',
      'results': 'النتائج',
      'settings': 'الإعدادات',
      'listen': 'استماع',
      'speak': 'تحدث',
      'stop': 'إيقاف',
      'recording_saved': 'تم حفظ التسجيل بنجاح!',
      'try_again': 'حاول مجددًا',
      'next_sentence': 'الجملة التالية',
      'good_job': 'أحسنت!',
      'no_result_yet': 'أكمل تدريبًا على جملة لترى نتيجتك هنا.',
      'sound': 'الصوت',
      'language': 'لغة الواجهة',
      'choose_language': 'اختر لغة التطبيق',
      'about': 'عن EchoSpeak',
      'about_text':
          'يساعدك EchoSpeak على التدرّب على التحدث بالإنجليزية، جملة قصيرة تلو الأخرى.',
      'mic_permission_title': 'إذن الميكروفون مطلوب',
      'mic_permission_body':
          'يحتاج EchoSpeak إلى إذن الميكروفون لتسجيل تدريبك. يرجى تفعيله من إعدادات جهازك.',
      'ok': 'حسنًا',
      'open_settings': 'فتح الإعدادات',
    },

    'fr': {
      'welcome': 'Bienvenue sur EchoSpeak',
      'welcome_sub':
          'Entraînez-vous à parler et améliorez votre prononciation, phrase après phrase.',
      'start_speaking': 'Commencer à parler',
      'what_you_can_do': 'Ce que vous pouvez faire',
      'feature_1': 'Écouter la bonne prononciation',
      'feature_2': 'Pratiquer à voix haute',
      'feature_3': 'Suivre vos tentatives',
      'home': 'Accueil',
      'practice': 'Pratique',
      'results': 'Résultats',
      'settings': 'Paramètres',
      'listen': 'Écouter',
      'speak': 'Parler',
      'stop': 'Arrêter',
      'recording_saved': 'Enregistrement sauvegardé !',
      'try_again': 'Réessayer',
      'next_sentence': 'Phrase suivante',
      'good_job': 'Bravo !',
      'no_result_yet': 'Terminez une phrase pour voir votre résultat ici.',
      'sound': 'Son',
      'language': 'Langue de l’interface',
      'choose_language': 'Choisissez la langue de l’application',
      'about': 'À propos d’EchoSpeak',
      'about_text':
          'EchoSpeak vous aide à pratiquer l’anglais, une courte phrase à la fois.',
      'mic_permission_title': 'Autorisation du microphone requise',
      'mic_permission_body':
          'EchoSpeak a besoin du microphone pour enregistrer votre pratique.',
      'ok': 'OK',
      'open_settings': 'Ouvrir les paramètres',
    },

    'es': {
      'welcome': 'Bienvenido a EchoSpeak',
      'welcome_sub':
          'Practica tu inglés y mejora tu pronunciación, una frase a la vez.',
      'start_speaking': 'Empezar a hablar',
      'what_you_can_do': 'Lo que puedes hacer',
      'feature_1': 'Escuchar la pronunciación correcta',
      'feature_2': 'Practicar hablando en voz alta',
      'feature_3': 'Seguir tus intentos',
      'home': 'Inicio',
      'practice': 'Práctica',
      'results': 'Resultados',
      'settings': 'Ajustes',
      'listen': 'Escuchar',
      'speak': 'Hablar',
      'stop': 'Detener',
      'recording_saved': '¡Grabación guardada correctamente!',
      'try_again': 'Intentar de nuevo',
      'next_sentence': 'Siguiente frase',
      'good_job': '¡Buen trabajo!',
      'no_result_yet': 'Completa una frase para ver tu resultado aquí.',
      'sound': 'Sonido',
      'language': 'Idioma de la interfaz',
      'choose_language': 'Elige el idioma de la aplicación',
      'about': 'Acerca de EchoSpeak',
      'about_text':
          'EchoSpeak te ayuda a practicar inglés, una frase corta a la vez.',
      'mic_permission_title': 'Se necesita permiso del micrófono',
      'mic_permission_body':
          'EchoSpeak necesita acceso al micrófono para grabar tu práctica.',
      'ok': 'Aceptar',
      'open_settings': 'Abrir ajustes',
    },

    'de': {
      'welcome': 'Willkommen bei EchoSpeak',
      'welcome_sub':
          'Übe Englisch und verbessere deine Aussprache, Satz für Satz.',
      'start_speaking': 'Sprechen beginnen',
      'what_you_can_do': 'Was du tun kannst',
      'feature_1': 'Richtige Aussprache anhören',
      'feature_2': 'Lautes Sprechen üben',
      'feature_3': 'Deine Versuche verfolgen',
      'home': 'Startseite',
      'practice': 'Üben',
      'results': 'Ergebnisse',
      'settings': 'Einstellungen',
      'listen': 'Anhören',
      'speak': 'Sprechen',
      'stop': 'Stoppen',
      'recording_saved': 'Aufnahme erfolgreich gespeichert!',
      'try_again': 'Erneut versuchen',
      'next_sentence': 'Nächster Satz',
      'good_job': 'Gut gemacht!',
      'no_result_yet': 'Übe einen Satz, um dein Ergebnis hier zu sehen.',
      'sound': 'Ton',
      'language': 'Oberflächensprache',
      'choose_language': 'Wähle die Sprache der App',
      'about': 'Über EchoSpeak',
      'about_text':
          'EchoSpeak hilft dir, Englisch zu üben, einen kurzen Satz nach dem anderen.',
      'mic_permission_title': 'Mikrofonberechtigung erforderlich',
      'mic_permission_body':
          'EchoSpeak benötigt Zugriff auf das Mikrofon, um deine Übungen aufzunehmen.',
      'ok': 'OK',
      'open_settings': 'Einstellungen öffnen',
    },

    'it': {
      'welcome': 'Benvenuto su EchoSpeak',
      'welcome_sub':
          'Pratica l’inglese e migliora la pronuncia, una frase alla volta.',
      'start_speaking': 'Inizia a parlare',
      'what_you_can_do': 'Cosa puoi fare',
      'feature_1': 'Ascoltare la pronuncia corretta',
      'feature_2': 'Esercitarti a parlare ad alta voce',
      'feature_3': 'Seguire i tuoi tentativi',
      'home': 'Home',
      'practice': 'Pratica',
      'results': 'Risultati',
      'settings': 'Impostazioni',
      'listen': 'Ascolta',
      'speak': 'Parla',
      'stop': 'Ferma',
      'recording_saved': 'Registrazione salvata con successo!',
      'try_again': 'Riprova',
      'next_sentence': 'Frase successiva',
      'good_job': 'Ottimo lavoro!',
      'no_result_yet': 'Completa una frase per vedere qui il risultato.',
      'sound': 'Suono',
      'language': 'Lingua dell’interfaccia',
      'choose_language': 'Scegli la lingua dell’app',
      'about': 'Informazioni su EchoSpeak',
      'about_text':
          'EchoSpeak ti aiuta a praticare l’inglese, una breve frase alla volta.',
      'mic_permission_title': 'È necessaria l’autorizzazione del microfono',
      'mic_permission_body':
          'EchoSpeak necessita dell’accesso al microfono per registrare la tua pratica.',
      'ok': 'OK',
      'open_settings': 'Apri impostazioni',
    },

    'tr': {
      'welcome': 'EchoSpeak’e Hoş Geldin',
      'welcome_sub':
          'İngilizce konuşma pratiği yap ve telaffuzunu cümle cümle geliştir.',
      'start_speaking': 'Konuşmaya Başla',
      'what_you_can_do': 'Neler yapabilirsin',
      'feature_1': 'Doğru telaffuzu dinle',
      'feature_2': 'Sesli konuşma pratiği yap',
      'feature_3': 'Denemelerini takip et',
      'home': 'Ana Sayfa',
      'practice': 'Pratik',
      'results': 'Sonuçlar',
      'settings': 'Ayarlar',
      'listen': 'Dinle',
      'speak': 'Konuş',
      'stop': 'Durdur',
      'recording_saved': 'Kayıt başarıyla kaydedildi!',
      'try_again': 'Tekrar Dene',
      'next_sentence': 'Sonraki Cümle',
      'good_job': 'Harika iş!',
      'no_result_yet': 'Sonucunu görmek için bir cümle üzerinde pratik yap.',
      'sound': 'Ses',
      'language': 'Arayüz Dili',
      'choose_language': 'Uygulama dilini seç',
      'about': 'EchoSpeak Hakkında',
      'about_text':
          'EchoSpeak, kısa cümlelerle İngilizce konuşma pratiği yapmana yardımcı olur.',
      'mic_permission_title': 'Mikrofon izni gerekli',
      'mic_permission_body':
          'EchoSpeak pratiğini kaydetmek için mikrofon erişimine ihtiyaç duyar.',
      'ok': 'Tamam',
      'open_settings': 'Ayarları Aç',
    },

    'pt': {
      'welcome': 'Bem-vindo ao EchoSpeak',
      'welcome_sub':
          'Pratique inglês e melhore sua pronúncia, uma frase de cada vez.',
      'start_speaking': 'Começar a falar',
      'what_you_can_do': 'O que você pode fazer',
      'feature_1': 'Ouvir a pronúncia correta',
      'feature_2': 'Praticar falando em voz alta',
      'feature_3': 'Acompanhar suas tentativas',
      'home': 'Início',
      'practice': 'Prática',
      'results': 'Resultados',
      'settings': 'Configurações',
      'listen': 'Ouvir',
      'speak': 'Falar',
      'stop': 'Parar',
      'recording_saved': 'Gravação salva com sucesso!',
      'try_again': 'Tentar novamente',
      'next_sentence': 'Próxima frase',
      'good_job': 'Bom trabalho!',
      'no_result_yet': 'Complete uma frase para ver seu resultado aqui.',
      'sound': 'Som',
      'language': 'Idioma da interface',
      'choose_language': 'Escolha o idioma do aplicativo',
      'about': 'Sobre o EchoSpeak',
      'about_text':
          'O EchoSpeak ajuda você a praticar inglês, uma frase curta de cada vez.',
      'mic_permission_title': 'Permissão do microfone necessária',
      'mic_permission_body':
          'O EchoSpeak precisa de acesso ao microfone para gravar sua prática.',
      'ok': 'OK',
      'open_settings': 'Abrir configurações',
    },

    'ja': {
      'welcome': 'EchoSpeakへようこそ',
      'welcome_sub': '一文ずつ英語を話す練習をして、発音を上達させましょう。',
      'start_speaking': 'スピーキングを始める',
      'what_you_can_do': 'できること',
      'feature_1': '正しい発音を聞く',
      'feature_2': '声に出して練習する',
      'feature_3': '練習履歴を確認する',
      'home': 'ホーム',
      'practice': '練習',
      'results': '結果',
      'settings': '設定',
      'listen': '聞く',
      'speak': '話す',
      'stop': '停止',
      'recording_saved': '録音を保存しました！',
      'try_again': 'もう一度',
      'next_sentence': '次の文',
      'good_job': 'よくできました！',
      'no_result_yet': '練習すると、ここに結果が表示されます。',
      'sound': 'サウンド',
      'language': '表示言語',
      'choose_language': 'アプリの言語を選択',
      'about': 'EchoSpeakについて',
      'about_text': 'EchoSpeakは短い英文を使って英会話の練習をサポートします。',
      'mic_permission_title': 'マイクの許可が必要です',
      'mic_permission_body': '練習を録音するためにマイクへのアクセスが必要です。',
      'ok': 'OK',
      'open_settings': '設定を開く',
    },

    'ko': {
      'welcome': 'EchoSpeak에 오신 것을 환영합니다',
      'welcome_sub': '한 문장씩 영어 말하기와 발음을 연습해 보세요.',
      'start_speaking': '말하기 시작',
      'what_you_can_do': '할 수 있는 것',
      'feature_1': '정확한 발음 듣기',
      'feature_2': '소리 내어 말하기 연습',
      'feature_3': '연습 기록 확인',
      'home': '홈',
      'practice': '연습',
      'results': '결과',
      'settings': '설정',
      'listen': '듣기',
      'speak': '말하기',
      'stop': '중지',
      'recording_saved': '녹음이 저장되었습니다!',
      'try_again': '다시 시도',
      'next_sentence': '다음 문장',
      'good_job': '잘했어요!',
      'no_result_yet': '문장을 연습하면 여기에 결과가 표시됩니다.',
      'sound': '소리',
      'language': '인터페이스 언어',
      'choose_language': '앱 언어를 선택하세요',
      'about': 'EchoSpeak 정보',
      'about_text':
          'EchoSpeak는 짧은 문장을 통해 영어 말하기 연습을 도와줍니다.',
      'mic_permission_title': '마이크 권한이 필요합니다',
      'mic_permission_body':
          '연습을 녹음하려면 EchoSpeak에 마이크 접근 권한이 필요합니다.',
      'ok': '확인',
      'open_settings': '설정 열기',
    },

    'zh': {
      'welcome': '欢迎使用 EchoSpeak',
      'welcome_sub': '通过一句一句的练习，提高你的英语口语和发音。',
      'start_speaking': '开始练习',
      'what_you_can_do': '你可以做什么',
      'feature_1': '听正确的发音',
      'feature_2': '大声练习口语',
      'feature_3': '查看你的练习记录',
      'home': '首页',
      'practice': '练习',
      'results': '结果',
      'settings': '设置',
      'listen': '听',
      'speak': '说',
      'stop': '停止',
      'recording_saved': '录音保存成功！',
      'try_again': '再试一次',
      'next_sentence': '下一句',
      'good_job': '做得很好！',
      'no_result_yet': '完成一句练习后，你的结果会显示在这里。',
      'sound': '声音',
      'language': '界面语言',
      'choose_language': '选择应用语言',
      'about': '关于 EchoSpeak',
      'about_text': 'EchoSpeak通过短句帮助你练习英语口语。',
      'mic_permission_title': '需要麦克风权限',
      'mic_permission_body': 'EchoSpeak需要麦克风权限来录制你的练习。',
      'ok': '确定',
      'open_settings': '打开设置',
    },
  };

  static String get(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['en']![key] ?? key;
  }
}
