class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'welcome': 'Welcome to EchoSpeak',
      'welcome_sub': 'Practice speaking and improve your pronunciation, one sentence at a time.',
      'start_speaking': 'Start Speaking',
      'what_you_can_do': 'What you can do',
      'feature_1': 'Listen to correct pronunciation',
      'feature_2': 'Practice speaking out loud',
      'feature_3': 'Track your attempts',
      'home': 'Home',
      'practice': 'Practice',
      'results': 'Results',
      'settings': 'Settings',
      'listen': 'Listen',
      'speak': 'Speak',
      'stop': 'Stop',
      'recording_saved': 'Recording saved successfully!',
      'try_again': 'Try Again',
      'next_sentence': 'Next Sentence',
      'good_job': 'Good job!',
      'no_result_yet': 'Complete a practice sentence to see your result here.',
      'sound': 'Sound',
      'language': 'Interface Language',
      'about': 'About EchoSpeak',
      'about_text': 'EchoSpeak helps you practice English speaking, one short sentence at a time. Phase 1 focuses on the core practice flow — pronunciation analysis is coming in a future update.',
      'mic_permission_title': 'Microphone permission needed',
      'mic_permission_body': 'EchoSpeak needs microphone access to record your practice. Please allow it from your device settings.',
      'ok': 'OK',
      'open_settings': 'Open Settings',
    },
    'ar': {
      'welcome': 'مرحبًا بك في EchoSpeak',
      'welcome_sub': 'تدرّب على النطق وتحدّث الإنجليزية جملة بجملة.',
      'start_speaking': 'ابدأ التدريب',
      'what_you_can_do': 'ماذا تستطيع أن تفعل',
      'feature_1': 'استمع للنطق الصحيح',
      'feature_2': 'تدرّب على التحدث بصوت عالٍ',
      'feature_3': 'تابع محاولاتك',
      'home': 'الرئيسية',
      'practice': 'التدريب',
      'results': 'النتائج',
      'settings': 'الإعدادات',
      'listen': 'استماع',
      'speak': 'تحدّث',
      'stop': 'إيقاف',
      'recording_saved': 'تم حفظ التسجيل بنجاح!',
      'try_again': 'حاول مجددًا',
      'next_sentence': 'الجملة التالية',
      'good_job': 'أحسنت!',
      'no_result_yet': 'أكمل تدريبًا على جملة لترى نتيجتك هنا.',
      'sound': 'الصوت',
      'language': 'لغة الواجهة',
      'about': 'عن EchoSpeak',
      'about_text': 'يساعدك EchoSpeak على التدرّب على النطق والتحدث بالإنجليزية جملة قصيرة تلو الأخرى. تركّز المرحلة الأولى على تجربة التدريب الأساسية.',
      'mic_permission_title': 'إذن الميكروفون مطلوب',
      'mic_permission_body': 'يحتاج EchoSpeak إلى إذن الميكروفون لتسجيل تدريبك. الرجاء تفعيله من إعدادات جهازك.',
      'ok': 'حسنًا',
      'open_settings': 'فتح الإعدادات',
    },
  };

  static String get(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['en']![key] ?? key;
  }
}
